version: '3'

services:
  web:
    container_name: project_nginx
    image: nginx
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8888:80"
    depends_on:
      - app

  app:
    container_name: project_app
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'laravel_db'
      MYSQL_ROOT_PASSWORD: root
    ports:
        -   '8101:3306'
    container_name: project_db
    user: mysql
